# Generated by Django 5.1 on 2024-08-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attributevalue_attribute_attributevalue_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='category',
            new_name='product',
        ),
    ]
