# Generated by Django 5.1 on 2024-08-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_attribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
    ]
